[2022-12-22 15:20:44,914] root - INFO ------------------------------ Spliting the model ready data into train and test files. ------------------------------
[2022-12-22 15:20:44,914] root - INFO Reading Parameters.
[2022-12-22 15:20:44,922] root - INFO Reading test and train data.
[2022-12-22 15:20:44,977] root - INFO Splitting x_train, y_train, x_test and y_test.
[2022-12-22 15:20:44,981] root - INFO Scaling the independent features.
[2022-12-22 15:20:44,998] root - INFO Setting up mlflow tracking uri.
[2022-12-22 15:20:44,998] root - INFO Setting up mlflow experiment as XGBoostRegressor.
[2022-12-22 15:20:47,120] urllib3.connectionpool - WARNING Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B746FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=XGBoostRegressor
[2022-12-22 15:20:53,153] urllib3.connectionpool - WARNING Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B779390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=XGBoostRegressor
[2022-12-22 15:21:03,186] urllib3.connectionpool - WARNING Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B7723D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=XGBoostRegressor
[2022-12-22 15:21:21,232] urllib3.connectionpool - WARNING Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B772B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=XGBoostRegressor
[2022-12-22 15:21:55,253] urllib3.connectionpool - WARNING Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B773590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=XGBoostRegressor
[2022-12-22 15:21:59,367] urllib3.connectionpool - WARNING Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B74C610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/list?view_type=ALL
[2022-12-22 15:22:05,403] urllib3.connectionpool - WARNING Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B781CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/list?view_type=ALL
[2022-12-22 15:22:15,423] urllib3.connectionpool - WARNING Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B783350>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/list?view_type=ALL
[2022-12-22 15:22:33,455] urllib3.connectionpool - WARNING Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B790150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/list?view_type=ALL
[2022-12-22 15:23:07,472] urllib3.connectionpool - WARNING Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B790E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/list?view_type=ALL
[2022-12-22 15:23:09,511] root - ERROR 
        Error occured in script: 
        [ C:\Data-Science-Projects\Metro-Interstate-Traffic-Analysis\src\train_and_evaluate.py ] at 
        try block line number: [59] and exception block line number: [120] 
        error message: [API request to http://127.0.0.1:1234/api/2.0/mlflow/experiments/list failed with exception HTTPConnectionPool(host='127.0.0.1', port=1234): Max retries exceeded with url: /api/2.0/mlflow/experiments/list?view_type=ALL (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF1B791DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
        
